name: Dota 2 Fantasy Stats Extended

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Build Clarity
      run: |
        git clone https://github.com/skadistats/clarity.git
        cd clarity
        ./gradlew build

    - name: Run Dota Fantasy Script
      env:
        OPENDOTA_API_KEY: ${{ secrets.OPENDOTA_API_KEY }}
      run: |
        cd ..
        java -jar clarity/build/libs/clarity-3.1.1.jar --league TI14 --output reports/ti14_summary.csv
        java -jar clarity/build/libs/clarity-3.1.1.jar --league EWC --output reports/ewc_summary.csv
