name: Dota 2 Fantasy Stats

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run Dota Fantasy Script
      env:
        OPENDOTA_API_KEY: ${{ secrets.OPENDOTA_API_KEY }}
      run: python scripts/fetch_dota_fantasy.py
