name: TI25 Bracket Predictor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build input.txt from Liquipedia (Group Stage)
        run: python dota_bitch/build_input.py

      - name: Sanity check files before prediction
        run: |
          echo "Top of predictor:"
          head -n 5 ti25_bracket_predictor.py || true
          echo "Input size:"
          wc -l input.txt || true
          ls -la

      - name: Run bracket predictor
        env:
          OPENDOTA_API_KEY: ${{ secrets.OPENDOTA_API_KEY }}
        run: python ti25_bracket_predictor.py < input.txt

      - name: Verify output exists
        run: |
          test -f bracket_prediction.md
          ls -lh bracket_prediction.md

      - name: Upload bracket prediction
        uses: actions/upload-artifact@v4
        with:
          name: ti25-bracket
          path: bracket_prediction.md
          if-no-files-found: error
